version: "2.0"

services:

  #  typescript application configuration

  typescript-backend:
    image: node:18-alpine
    container_name: typescript-backend
    restart: unless-stopped
    ports:
      - 6001:5000
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn install &&  yarn start:dev"

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - /var/lib/mysql/boilerplate:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    restart: unless-stopped
    
  adminer:
      image: adminer
      restart: always
      ports:
        - 84:8080
        
  redis:
      image: redis:6.2
      container_name: redis
      restart: unless-stopped
      volumes:
          -  /var/lib/redis/boilerplate:/data





# End of application configuration
